# keepassxc
# Autogenerated from man page /usr/share/man/man1/keepassxc.1.gz
complete -c keepassxc -s h -l help --description 'Displays this help.'
complete -c keepassxc -s v -l version --description 'Displays version information.'
complete -c keepassxc -l config --description 'Path to a custom config file.'
complete -c keepassxc -l keyfile --description 'Key file of the database.'
complete -c keepassxc -l pw-stdin --description 'Read password of the database from stdin.'
complete -c keepassxc -l pw -l parent-window --description 'Parent window handle.'
complete -c keepassxc -l debug-info --description 'Displays debugging information.'

