# xboxdrv
# Autogenerated from man page /usr/share/man/man1/xboxdrv.1.gz
complete -c xboxdrv -s V -l version --description 'Print the version number and exit.'
complete -c xboxdrv -l buttonmap --description 'Button remapping is available via the \\*(T<--buttonmap\\*(T> option.'
complete -c xboxdrv -l evdev-absmap --description 'section for better readability.'
complete -c xboxdrv -l device-names --description '.'
complete -c xboxdrv -l device-usbids --description '.'

