# xxh64sum
# Autogenerated from man page /usr/share/man/man1/xxh64sum.1.gz
complete -c xxh64sum -s V -l version --description 'Display xxhsum version and exits .'
complete -c xxh64sum -o HHASHTYPE --description 'Hash selection.  HASHTYPE means 0=32bits, 1=64bits, 2=128bits.'
complete -c xxh64sum -s q -l quiet --description 'Remove status messages like "Loading . " written to stderr .'
complete -c xxh64sum -l little-endian --description 'Set output hexadecimal checksum value as little endian convention.'
complete -c xxh64sum -s h -l help --description 'Display help and exit .'
complete -c xxh64sum -s c -l check --description 'Read xxHash sums from the FILEs and check them .'
complete -c xxh64sum -l strict --description 'Don\'t print OK for each successfully verified file .'
complete -c xxh64sum -l status --description 'Don\'t output anything, status code shows success .'
complete -c xxh64sum -s w -l warn --description 'Warn about improperly formatted checksum lines .'
complete -c xxh64sum -s b --description 'Benchmark mode.  See EXAMPLES for details.'
complete -c xxh64sum -o BBLOCKSIZE --description 'Only useful for benchmark mode (-b).  See EXAMPLES for details.'

